const base = require('./jest.config');

module.exports = {
  ...base,
  modulePathIgnorePatterns: ['<rootDir>/.stryker-tmp/'],
  testMatch: [
    '<rootDir>/__tests__/AppMonitoring.test.ts',
    '<rootDir>/__tests__/AutofillService.test.ts',
    '<rootDir>/__tests__/BackupModule.test.ts',
    '<rootDir>/__tests__/BackupHelpers.test.ts',
    '<rootDir>/__tests__/CloudSyncModule.test.ts',
    '<rootDir>/__tests__/DeltaSyncModule.test.ts',
    '<rootDir>/__tests__/EmergencyAccessModule.test.ts',
    '<rootDir>/__tests__/SecurityModule.test.ts',
    '<rootDir>/__tests__/SecurityAdvanced.test.ts',
    '<rootDir>/__tests__/SecurityPhase2.test.ts',
    '<rootDir>/__tests__/SecurityPhase3.test.ts',
    '<rootDir>/__tests__/SyncCryptoService.test.ts',
    '<rootDir>/__tests__/FileEncryptionModule.test.ts',
    '<rootDir>/__tests__/HIBPModule.test.ts',
    '<rootDir>/__tests__/ImportVersioning.test.ts',
    '<rootDir>/__tests__/VaultManager.test.ts',
    '<rootDir>/__tests__/IntegrityModule.test.ts',
    '<rootDir>/__tests__/PasskeyModule.test.ts',
    '<rootDir>/__tests__/PasskeyEnrollmentService.test.ts',
    '<rootDir>/__tests__/PasskeyRpApi.test.ts',
    '<rootDir>/__tests__/PasskeyBindingService.test.ts',
    '<rootDir>/__tests__/RecoveryModule.test.ts',
    '<rootDir>/__tests__/SearchService.test.ts',
    '<rootDir>/__tests__/SecureAppSettings.test.ts',
    '<rootDir>/__tests__/SecurityCenterService.test.ts',
    '<rootDir>/__tests__/SharedSpaceService.test.ts',
    '<rootDir>/__tests__/SharingAuditService.test.ts',
    '<rootDir>/__tests__/SyncConflictService.test.ts',
    '<rootDir>/__tests__/SyncDeviceService.test.ts',
    '<rootDir>/__tests__/SyncEnvelope.test.ts',
    '<rootDir>/__tests__/SyncManager.test.ts',
    '<rootDir>/__tests__/TOTPModule.test.ts',
    '<rootDir>/__tests__/WearOSModule.test.ts',
    '<rootDir>/__tests__/WearSyncCrypto.test.ts',
    '<rootDir>/__tests__/PasswordHistoryModule.test.ts',
  ],
};
